-- Mashico v8: horario, reservas, pagos e imágenes por WhatsApp.

ALTER TABLE business_settings
    ADD COLUMN IF NOT EXISTS assistant_name VARCHAR(80) NOT NULL DEFAULT 'Mashico',
    ADD COLUMN IF NOT EXISTS time_zone VARCHAR(80) NOT NULL DEFAULT 'America/Lima',
    ADD COLUMN IF NOT EXISTS attention_days VARCHAR(120) NOT NULL DEFAULT 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY',
    ADD COLUMN IF NOT EXISTS opening_time TIME NOT NULL DEFAULT '08:00',
    ADD COLUMN IF NOT EXISTS closing_time TIME NOT NULL DEFAULT '20:00',
    ADD COLUMN IF NOT EXISTS same_day_cutoff_time TIME NOT NULL DEFAULT '19:30',
    ADD COLUMN IF NOT EXISTS allow_next_day_reservations BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS reservation_slots VARCHAR(500) NOT NULL DEFAULT '08:00-10:00;10:00-12:00;12:00-14:00;14:00-16:00;16:00-18:00',
    ADD COLUMN IF NOT EXISTS send_product_images BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS yape_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS yape_number VARCHAR(30),
    ADD COLUMN IF NOT EXISTS yape_holder VARCHAR(160),
    ADD COLUMN IF NOT EXISTS yape_qr_url VARCHAR(800),
    ADD COLUMN IF NOT EXISTS plin_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS plin_number VARCHAR(30),
    ADD COLUMN IF NOT EXISTS plin_holder VARCHAR(160),
    ADD COLUMN IF NOT EXISTS plin_qr_url VARCHAR(800),
    ADD COLUMN IF NOT EXISTS transfer_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bank_account_type VARCHAR(80),
    ADD COLUMN IF NOT EXISTS bank_account_number VARCHAR(80),
    ADD COLUMN IF NOT EXISTS bank_cci VARCHAR(80),
    ADD COLUMN IF NOT EXISTS bank_holder VARCHAR(160);

ALTER TABLE customer_orders
    ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMPTZ;

ALTER TABLE chat_sessions DROP CONSTRAINT IF EXISTS ck_chat_state;
ALTER TABLE chat_sessions
    ADD CONSTRAINT ck_chat_state CHECK (state IN (
        'MAIN_MENU','SELECTING_CATEGORY','SELECTING_PRODUCT','ENTERING_QUANTITY','CART_DECISION',
        'SELECTING_FULFILLMENT','SELECTING_ZONE','ENTERING_ADDRESS','ENTERING_REFERENCE',
        'SELECTING_RESERVATION_SLOT','SELECTING_PAYMENT','CONFIRMING','HUMAN_HANDOFF'
    ));

CREATE INDEX IF NOT EXISTS idx_orders_scheduled_for
    ON customer_orders(scheduled_for)
    WHERE scheduled_for IS NOT NULL;

UPDATE business_settings
SET assistant_name = COALESCE(NULLIF(assistant_name, ''), 'Mashico'),
    time_zone = COALESCE(NULLIF(time_zone, ''), 'America/Lima'),
    attention_days = COALESCE(NULLIF(attention_days, ''), 'MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY'),
    reservation_slots = COALESCE(NULLIF(reservation_slots, ''), '08:00-10:00;10:00-12:00;12:00-14:00;14:00-16:00;16:00-18:00')
WHERE id = 1;
