package pe.laherradura.enums;

public enum ChatState { MAIN_MENU, SELECTING_CATEGORY, SELECTING_PRODUCT, ENTERING_QUANTITY, CART_DECISION, SELECTING_FULFILLMENT, SELECTING_ZONE, ENTERING_ADDRESS, ENTERING_REFERENCE, SELECTING_PAYMENT, CONFIRMING, HUMAN_HANDOFF }
