-- Esquema inicial para PostgreSQL / Supabase

CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'OPERATOR',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_app_users_role CHECK (role IN ('ADMIN', 'OPERATOR'))
);

CREATE TABLE IF NOT EXISTS business_settings (
    id BIGINT PRIMARY KEY,
    business_name VARCHAR(160) NOT NULL,
    phone VARCHAR(30),
    address VARCHAR(300),
    opening_hours VARCHAR(300),
    delivery_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    minimum_delivery_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'PEN',
    welcome_message VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(400),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL UNIQUE,
    description VARCHAR(800),
    price_per_unit NUMERIC(12,2) NOT NULL,
    unit VARCHAR(20) NOT NULL DEFAULT 'KG',
    stock_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
    minimum_quantity NUMERIC(12,3) NOT NULL DEFAULT 0.500,
    image_url VARCHAR(800),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT ck_products_unit CHECK (unit IN ('KG', 'UNIT', 'PACK')),
    CONSTRAINT ck_products_price CHECK (price_per_unit >= 0),
    CONSTRAINT ck_products_stock CHECK (stock_quantity >= 0),
    CONSTRAINT ck_products_minimum CHECK (minimum_quantity > 0)
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(30) NOT NULL UNIQUE,
    address VARCHAR(400),
    reference VARCHAR(400),
    zone VARCHAR(120),
    consent_marketing BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS delivery_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    fee NUMERIC(12,2) NOT NULL DEFAULT 0,
    minimum_order NUMERIC(12,2) NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_delivery_zone_fee CHECK (fee >= 0),
    CONSTRAINT ck_delivery_zone_minimum CHECK (minimum_order >= 0)
);

CREATE TABLE IF NOT EXISTS promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(800),
    promotional_price NUMERIC(12,2),
    start_date DATE,
    end_date DATE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    image_url VARCHAR(800),
    CONSTRAINT ck_promotions_price CHECK (promotional_price IS NULL OR promotional_price >= 0),
    CONSTRAINT ck_promotions_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    fulfillment_type VARCHAR(20) NOT NULL DEFAULT 'PICKUP',
    delivery_zone_id BIGINT,
    delivery_address VARCHAR(500),
    delivery_reference VARCHAR(500),
    payment_method VARCHAR(20) NOT NULL DEFAULT 'CASH',
    source VARCHAR(20) NOT NULL DEFAULT 'WHATSAPP',
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
    delivery_fee NUMERIC(12,2) NOT NULL DEFAULT 0,
    total NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_orders_delivery_zone FOREIGN KEY (delivery_zone_id) REFERENCES delivery_zones(id) ON DELETE SET NULL,
    CONSTRAINT ck_orders_status CHECK (status IN ('DRAFT','PENDING','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED')),
    CONSTRAINT ck_orders_fulfillment CHECK (fulfillment_type IN ('PICKUP','DELIVERY')),
    CONSTRAINT ck_orders_payment CHECK (payment_method IN ('CASH','YAPE','PLIN','TRANSFER')),
    CONSTRAINT ck_orders_source CHECK (source IN ('WHATSAPP','FACEBOOK','INSTAGRAM','WEB','STORE','PHONE')),
    CONSTRAINT ck_orders_amounts CHECK (subtotal >= 0 AND delivery_fee >= 0 AND total >= 0)
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    quantity NUMERIC(12,3) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES customer_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_amounts CHECK (unit_price >= 0 AND subtotal >= 0)
);

CREATE TABLE IF NOT EXISTS chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(30) NOT NULL UNIQUE,
    customer_id BIGINT,
    state VARCHAR(40) NOT NULL DEFAULT 'MAIN_MENU',
    context_json TEXT NOT NULL DEFAULT '{}',
    last_interaction TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_chat_sessions_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    CONSTRAINT ck_chat_state CHECK (state IN (
        'MAIN_MENU','SELECTING_CATEGORY','SELECTING_PRODUCT','ENTERING_QUANTITY','CART_DECISION',
        'SELECTING_FULFILLMENT','SELECTING_ZONE','ENTERING_ADDRESS','ENTERING_REFERENCE',
        'SELECTING_PAYMENT','CONFIRMING','HUMAN_HANDOFF'
    ))
);

CREATE TABLE IF NOT EXISTS whatsapp_message_log (
    message_id VARCHAR(120) PRIMARY KEY,
    phone VARCHAR(30),
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_active_featured ON products(active, featured);
CREATE INDEX IF NOT EXISTS idx_products_low_stock ON products(stock_quantity, minimum_quantity) WHERE active = TRUE;
CREATE INDEX IF NOT EXISTS idx_customers_created_at ON customers(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON customer_orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON customer_orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON customer_orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_chat_last_interaction ON chat_sessions(last_interaction DESC);
CREATE INDEX IF NOT EXISTS idx_whatsapp_processed_at ON whatsapp_message_log(processed_at DESC);

-- La aplicación accede mediante Spring Boot. Se bloquea el acceso directo
-- desde las claves públicas de Supabase al no definir políticas RLS.
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE business_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_message_log ENABLE ROW LEVEL SECURITY;
