-- Parche v9: locales, Google Maps y galería fotográfica del negocio.

CREATE TABLE IF NOT EXISTS store_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(300) NOT NULL,
    district VARCHAR(100),
    province VARCHAR(100),
    department VARCHAR(100),
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    google_place_id VARCHAR(255),
    google_maps_url VARCHAR(1000),
    google_maps_embed_url VARCHAR(1200),
    phone VARCHAR(30),
    whatsapp_number VARCHAR(30),
    reference_text VARCHAR(300),
    parking_information VARCHAR(300),
    is_main BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_store_location_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_store_location_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE IF NOT EXISTS store_location_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_location_id BIGINT NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    title VARCHAR(150),
    description VARCHAR(300),
    alt_text VARCHAR(200),
    image_type VARCHAR(30) NOT NULL DEFAULT 'GALLERY',
    display_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_store_location_images_location
        FOREIGN KEY (store_location_id) REFERENCES store_locations(id) ON DELETE CASCADE,
    CONSTRAINT ck_store_location_image_type CHECK (image_type IN (
        'COVER','FACADE','INTERIOR','COUNTER','PRODUCT_DISPLAY','PARKING','REFERENCE','GALLERY'
    )),
    CONSTRAINT ck_store_location_image_order CHECK (display_order >= 0)
);

CREATE INDEX IF NOT EXISTS idx_store_locations_active_main
    ON store_locations(is_active, is_main DESC, name);
CREATE UNIQUE INDEX IF NOT EXISTS uk_store_locations_one_main
    ON store_locations(is_main)
    WHERE is_main = TRUE AND is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_store_location_images_order
    ON store_location_images(store_location_id, is_visible, display_order, id);

INSERT INTO store_locations (
    name, address, phone, whatsapp_number, is_main, is_active
)
SELECT
    COALESCE(NULLIF(business_name, ''), 'Carnicería La Herradura'),
    COALESCE(NULLIF(address, ''), 'Dirección por configurar'),
    phone,
    phone,
    CASE WHEN address IS NULL OR BTRIM(address) = '' OR UPPER(address) LIKE '%PENDIENTE%' THEN FALSE ELSE TRUE END,
    CASE WHEN address IS NULL OR BTRIM(address) = '' OR UPPER(address) LIKE '%PENDIENTE%' THEN FALSE ELSE TRUE END
FROM business_settings
WHERE id = 1
  AND NOT EXISTS (SELECT 1 FROM store_locations);

ALTER TABLE store_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_location_images ENABLE ROW LEVEL SECURITY;
